export interface AllWeatherInfo {
  latlon: null | LatlonType
  weatherDetail: null | WeatherType
  forecast: null | ForecastType
}

export interface FiveWeatherInfo {
  latlon: null | LatlonType
  weatherDetail: null | WeatherType
  forecast: null | ForecastType
  name: string
  units: 'imperial' | 'metric'
  id: string
}

export type LatlonType = typeof latLonConst
export type WeatherType = typeof weather
export type ForecastType = typeof forecast

const latLonConst = {
  name: 'London',
  local_names: {
    ms: 'London',
    gu: 'લંડન',
    is: 'London',
    wa: 'Londe',
    mg: 'Lôndôna',
    gl: 'Londres',
    om: 'Landan',
    ku: 'London',
    tw: 'London',
    mk: 'Лондон',
    ee: 'London',
    fj: 'Lodoni',
    gd: 'Lunnainn',
    ky: 'Лондон',
    yo: 'Lọndọnu',
    zu: 'ILondon',
    bg: 'Лондон',
    tk: 'London',
    co: 'Londra',
    sh: 'London',
    de: 'London',
    kl: 'London',
    bi: 'London',
    km: 'ឡុងដ៍',
    lt: 'Londonas',
    fi: 'Lontoo',
    fy: 'Londen',
    ba: 'Лондон',
    sc: 'Londra',
    feature_name: 'London',
    ja: 'ロンドン',
    am: 'ለንደን',
    sk: 'Londýn',
    mr: 'लंडन',
    es: 'Londres',
    sq: 'Londra',
    te: 'లండన్',
    br: 'Londrez',
    uz: 'London',
    da: 'London',
    sw: 'London',
    fa: 'لندن',
    sr: 'Лондон',
    cu: 'Лондонъ',
    ln: 'Lóndɛlɛ',
    na: 'London',
    wo: 'Londar',
    ig: 'London',
    to: 'Lonitoni',
    ta: 'இலண்டன்',
    mt: 'Londra',
    ar: 'لندن',
    su: 'London',
    ab: 'Лондон',
    ps: 'لندن',
    bm: 'London',
    mi: 'Rānana',
    kn: 'ಲಂಡನ್',
    kv: 'Лондон',
    os: 'Лондон',
    bn: 'লন্ডন',
    li: 'Londe',
    vi: 'Luân Đôn',
    zh: '伦敦',
    eo: 'Londono',
    ha: 'Landan',
    tt: 'Лондон',
    lb: 'London',
    ce: 'Лондон',
    hu: 'London',
    it: 'Londra',
    tl: 'Londres',
    pl: 'Londyn',
    sm: 'Lonetona',
    en: 'London',
    vo: 'London',
    el: 'Λονδίνο',
    sn: 'London',
    fr: 'Londres',
    cs: 'Londýn',
    io: 'London',
    hi: 'लंदन',
    et: 'London',
    pa: 'ਲੰਡਨ',
    av: 'Лондон',
    ko: '런던',
    bh: 'लंदन',
    yi: 'לאנדאן',
    sa: 'लन्डन्',
    sl: 'London',
    hr: 'London',
    si: 'ලන්ඩන්',
    so: 'London',
    gn: 'Lóndyre',
    ay: 'London',
    se: 'London',
    sd: 'لنڊن',
    af: 'Londen',
    ga: 'Londain',
    or: 'ଲଣ୍ଡନ',
    ia: 'London',
    ie: 'London',
    ug: 'لوندۇن',
    nl: 'Londen',
    gv: 'Lunnin',
    qu: 'London',
    be: 'Лондан',
    an: 'Londres',
    fo: 'London',
    hy: 'Լոնդոն',
    nv: 'Tooh Dineʼé Bikin Haalʼá',
    bo: 'ལོན་ཊོན།',
    ascii: 'London',
    id: 'London',
    lv: 'Londona',
    ca: 'Londres',
    no: 'London',
    nn: 'London',
    ml: 'ലണ്ടൻ',
    my: 'လန်ဒန်မြို့',
    ne: 'लन्डन',
    he: 'לונדון',
    cy: 'Llundain',
    lo: 'ລອນດອນ',
    jv: 'London',
    sv: 'London',
    mn: 'Лондон',
    tg: 'Лондон',
    kw: 'Loundres',
    cv: 'Лондон',
    az: 'London',
    oc: 'Londres',
    th: 'ลอนดอน',
    ru: 'Лондон',
    ny: 'London',
    bs: 'London',
    st: 'London',
    ro: 'Londra',
    rm: 'Londra',
    ff: 'London',
    kk: 'Лондон',
    uk: 'Лондон',
    pt: 'Londres',
    tr: 'Londra',
    eu: 'Londres',
    ht: 'Lonn',
    ka: 'ლონდონი',
    ur: 'علاقہ لندن',
  },
  lat: 51.5073219,
  lon: -0.1276474,
  country: 'GB',
  state: 'England',
}

const weather = {
  coord: {
    lon: 7.367,
    lat: 45.133,
  },
  weather: [
    {
      id: 501,
      main: 'Rain',
      description: 'moderate rain',
      icon: '10d',
    },
  ],
  base: 'stations',
  main: {
    temp: 284.2,
    feels_like: 282.93,
    temp_min: 283.06,
    temp_max: 286.82,
    pressure: 1021,
    humidity: 60,
    sea_level: 1021,
    grnd_level: 910,
  },
  visibility: 10000,
  wind: {
    speed: 4.09,
    deg: 121,
    gust: 3.47,
  },
  rain: {
    '1h': 2.73,
  },
  clouds: {
    all: 83,
  },
  dt: 1726660758,
  sys: {
    type: 1,
    id: 6736,
    country: 'IT',
    sunrise: 1726636384,
    sunset: 1726680975,
  },
  timezone: 7200,
  id: 3165523,
  name: 'Province of Turin',
  cod: 200,
}

const forecast = {
  cod: '200',
  message: 0,
  cnt: 40,
  list: [
    {
      dt: 1661871600,
      main: {
        temp: 296.76,
        feels_like: 296.98,
        temp_min: 296.76,
        temp_max: 297.87,
        pressure: 1015,
        sea_level: 1015,
        grnd_level: 933,
        humidity: 69,
        temp_kf: -1.11,
      },
      weather: [
        {
          id: 500,
          main: 'Rain',
          description: 'light rain',
          icon: '10d',
        },
      ],
      clouds: {
        all: 100,
      },
      wind: {
        speed: 0.62,
        deg: 349,
        gust: 1.18,
      },
      visibility: 10000,
      pop: 0.32,
      rain: {
        '3h': 0.26,
      },
      sys: {
        pod: 'd',
      },
      dt_txt: '2022-08-30 15:00:00',
    },
    {
      dt: 1661882400,
      main: {
        temp: 295.45,
        feels_like: 295.59,
        temp_min: 292.84,
        temp_max: 295.45,
        pressure: 1015,
        sea_level: 1015,
        grnd_level: 931,
        humidity: 71,
        temp_kf: 2.61,
      },
      weather: [
        {
          id: 500,
          main: 'Rain',
          description: 'light rain',
          icon: '10n',
        },
      ],
      clouds: {
        all: 96,
      },
      wind: {
        speed: 1.97,
        deg: 157,
        gust: 3.39,
      },
      visibility: 10000,
      pop: 0.33,
      rain: {
        '3h': 0.57,
      },
      sys: {
        pod: 'n',
      },
      dt_txt: '2022-08-30 18:00:00',
    },
    {
      dt: 1661893200,
      main: {
        temp: 292.46,
        feels_like: 292.54,
        temp_min: 290.31,
        temp_max: 292.46,
        pressure: 1015,
        sea_level: 1015,
        grnd_level: 931,
        humidity: 80,
        temp_kf: 2.15,
      },
      weather: [
        {
          id: 500,
          main: 'Rain',
          description: 'light rain',
          icon: '10n',
        },
      ],
      clouds: {
        all: 68,
      },
      wind: {
        speed: 2.66,
        deg: 210,
        gust: 3.58,
      },
      visibility: 10000,
      pop: 0.7,
      rain: {
        '3h': 0.49,
      },
      sys: {
        pod: 'n',
      },
      dt_txt: '2022-08-30 21:00:00',
    },
    {
      dt: 1662292800,
      main: {
        temp: 294.93,
        feels_like: 294.83,
        temp_min: 294.93,
        temp_max: 294.93,
        pressure: 1018,
        sea_level: 1018,
        grnd_level: 935,
        humidity: 64,
        temp_kf: 0,
      },
      weather: [
        {
          id: 804,
          main: 'Clouds',
          description: 'overcast clouds',
          icon: '04d',
        },
      ],
      clouds: {
        all: 88,
      },
      wind: {
        speed: 1.14,
        deg: 17,
        gust: 1.57,
      },
      visibility: 10000,
      pop: 0,
      sys: {
        pod: 'd',
      },
      dt_txt: '2022-09-04 12:00:00',
    },
  ],
  city: {
    id: 3163858,
    name: 'Zocca',
    coord: {
      lat: 44.34,
      lon: 10.99,
    },
    country: 'IT',
    population: 4593,
    timezone: 7200,
    sunrise: 1661834187,
    sunset: 1661882248,
  },
}
